version: '3'
services:
  apache-web:
    build: .
    image: apache-web:v1
    ports:
      - 8080:80
    container_name: apache-container
    networks: net1
  
  mysql-db:
    container_name: mysql-container
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /opt/mysql:/var/lib/mysql
    networks: net1

networks:
  net:
    name: net1
    
    

    
